#!/usr/bin/env node

const fs = require('fs/promises');
const path = require('path');

async function resetData() {
    const simDataDir = path.join(__dirname, '..', 'sim_data');

    // Ensure directory exists (handles fresh deploys)
    try {
        await fs.mkdir(simDataDir, { recursive: true });
    } catch {}

    // Files to reset (clear completely)
    const filesToReset = [
        'cycles.jsonl',
        'portfolio.jsonl',
        'orders.jsonl',
        'pairs_state.json'
    ];

    // Files to keep (markets.json, pairs.json get regenerated)
    // pairs.json is regenerated by pair builder
    // markets.json is refreshed by main.ts

    console.log('Resetting simulation data files...');

    for (const file of filesToReset) {
        const filePath = path.join(simDataDir, file);
        try {
            // Create empty file (or empty object for JSON)
            if (file.endsWith('.json')) {
                await fs.writeFile(filePath, '{}', 'utf8');
            } else {
                await fs.writeFile(filePath, '', 'utf8');
            }
            console.log(`✓ Reset ${file}`);
        } catch (error) {
            console.error(`✗ Failed to reset ${file}:`, error.message);
        }
    }

    console.log('Data reset complete. Ready for fresh simulation!');
}

resetData().catch(console.error);
